import random, os, math, PIL
from collections import defaultdict
from copy import deepcopy
from typing import *

from concurrent.futures import ThreadPoolExecutor

from PIL import Image, ImageChops
import PIL.Image
from PIL.ImageOps import exif_transpose

import torch
from torch.utils.data import ConcatDataset, Dataset, Subset
from torch.utils.data.distributed import DistributedSampler

import torchvision.transforms.functional as F

from alpha.utils import load_json_file


class DistributedWeightedSampler(DistributedSampler):
    def __init__(self, dataset, weights, num_samples=None, replacement=True, num_replicas=None, rank=None, seed=0, drop_last=False):
        """
        Custom Sampler combining DistributedSampler and WeightedRandomSampler functionalities.
        """
        # Initialize parent class, automatically getting num_replicas (world_size) and rank
        super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=False, seed=seed, drop_last=drop_last)
        
        self.weights = torch.as_tensor(weights, dtype=torch.double)
        self.replacement = replacement
        
        # If num_samples is not specified, default to sampling the entire dataset length
        if num_samples is None:
            num_samples = len(self.dataset)
        self.num_samples = num_samples
        
        # Calculate the number of samples each card needs to process, ensuring the number of batches processed by all cards is absolutely consistent
        if self.drop_last and self.num_samples % self.num_replicas != 0:
            self.num_samples_per_replica = math.ceil(
                (self.num_samples - self.num_replicas) / self.num_replicas
            )
        else:
            self.num_samples_per_replica = math.ceil(self.num_samples / self.num_replicas)
            
        # Calculate global total samples (usually equals num_samples, unless there is padding)
        self.total_size = self.num_samples_per_replica * self.num_replicas

    def __iter__(self):
        # 1. Extremely important: Use epoch + seed as the random seed
        # This guarantees (a) the global sequence generated by all cards in the same epoch is exactly the same; (b) sequences generated in different epochs are different
        g = torch.Generator()
        g.manual_seed(self.seed + self.epoch)
        
        # 2. From a global perspective, generate indices for all samples based on weights
        indices = torch.multinomial(
            self.weights, self.total_size, self.replacement, generator=g
        ).tolist()

        # 3. Distributed slicing: The current card only takes the part of data belonging to it
        # Example: 2 machines 16 cards, rank=0 takes [0, 16, 32...], rank=1 takes [1, 17, 33...]
        indices = indices[self.rank:self.total_size:self.num_replicas]
        
        assert len(indices) == self.num_samples_per_replica

        return iter(indices)

    def __len__(self):
        return self.num_samples_per_replica


class DatasetItemOverride(Dataset):
    def __init__(self, dataset: Dataset, overrides: Dict[str, Any]):
        self.dataset = dataset
        self.overrides = overrides

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, index):
        example = dict(self.dataset[index])
        example.update(self.overrides)
        return example

class DatasetManager:
    public_classes: Dict[str, Type] = {}
    public_default_class: Optional[Type] = None
    def __init__(self, config_path: str):
        self.config = load_json_file(config_path)
        self.default_class = None
        self.class_map = {}
        self.cache = {}

    def set_default_class(self, dataset_class: Type):
        """Set the default class for datasets."""
        self.default_class = dataset_class
        return self

    def register_class(self, class_type: Type, class_name: Optional[str] = None):
        """Register a dataset class with an optional name."""
        name = class_name or class_type.__name__
        self.class_map[name] = class_type

    def _load_dataset(self, name: str):
        """Lazy load a dataset by name."""
        if name in self.cache:
            return self.cache[name]

        dataset_config = self.config['datasets'].get(name)
        if not dataset_config:
            raise ValueError(f"Dataset {name} not found in configuration.")

        dataset_config = deepcopy(dataset_config)
        dataset_class = dataset_config.pop('class', self.default_class or self.__class__.public_default_class)
        if isinstance(dataset_class, str):
            dataset_class = self.class_map.get(dataset_class) or self.__class__.public_classes.get(dataset_class)
        if not dataset_class:
            raise ValueError(f"No class specified for dataset {name}, and no default class set.")

        # TODO: and another level, categorize by module name (current error: partial)
        params = deepcopy(self.config.get('default_init_params', {}))
        params.update(dataset_config)
        
        print(f"Instantiating dataset {name} with params: {params}")
        
        # Instantiate the dataset
        dataset = dataset_class(**params)
        self.cache[name] = dataset
        return dataset

    def get_split(self, split_name: str, enable_weight: bool = False, verbose: bool = False, max_workers: int = 16) -> Union[Dataset, Tuple[Dataset, List[float]]]:
        """Get concatenated datasets for a specific split using multithreading."""
        split_config = self.config['splits'].get(split_name)
        if not split_config:
            raise ValueError(f"Split {split_name} not found in configuration.")

        # Encapsulate the original logic into an independent function for thread calling
        def process_entry(entry: dict):
            if verbose:
                # Note: print might be out of order under multi-threading, just print simply here
                print(f"Loading dataset: {entry['dataset']}")
                
            dataset = self._load_dataset(entry['dataset'])

            if 'starts' in entry or 'ends' in entry:
                starts = entry.get('starts', 0)
                ends = entry.get('ends', len(dataset))
                while starts < 0:
                    starts += len(dataset)
                while ends < 0:
                    ends += len(dataset)
                dataset = Subset(dataset, range(starts, ends))

            if 'repeat' in entry:
                repeat = entry['repeat']
                indices = []
                for i in range(len(dataset)):
                    indices.extend([i] * repeat)
                dataset = Subset(dataset, indices)

            if 'sample' in entry:
                count = len(dataset)
                if 'ratio' in entry['sample']:
                    ratio = entry['sample'].get('ratio', 1.0)
                    count = min(count, int(len(dataset) * ratio))
                elif 'count' in entry['sample']:
                    cnt = entry['sample'].get('count', count)
                    count = min(count, cnt)
                seed = entry['sample'].get('seed', None)
                generator = random.Random(seed)
                indices = generator.sample(range(len(dataset)), count)
                dataset = Subset(dataset, indices)

            example_overrides = {}
            if "begin_with_bg" in entry:
                example_overrides["begin_with_bg"] = bool(entry["begin_with_bg"])
            if example_overrides:
                dataset = DatasetItemOverride(dataset, example_overrides)
            
            weight = entry.get('weight', 1.0)
            return dataset, weight
        
        # Use ThreadPoolExecutor for parallel loading
        datasets = []
        weights: List[float] = []
        
        # max_workers can be adjusted based on your CPU cores or I/O throughput
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            # executor.map returns results in the order of split_config, ensuring dataset order consistency
            results = list(executor.map(process_entry, split_config))

        # Collect results
        for dataset, weight in results:
            datasets.append(dataset)
            if enable_weight:
                weights.extend([weight] * len(dataset))

        if enable_weight:
            return ConcatDataset(datasets), weights
        else:
            return ConcatDataset(datasets)



def concat_images(images: List[Image.Image]) -> Image.Image:
    # Get height and width of all images, assuming all images have the same height
    if not images:
        raise ValueError("Image list cannot be empty")

    # Assume all images have consistent height, get height and width of the first image
    height = images[0].height
    width = sum(img.width for img in images)  # Calculate sum of all image widths
    
    # Create a new blank image, width is sum of all image widths, height remains unchanged, using RGBA mode
    new_image = Image.new('RGBA', (width, height))
    
    # Paste images
    x_offset = 0
    for img in images:
        new_image.paste(img, (x_offset, 0))
        x_offset += img.width
    
    return new_image


class TI2IDataset(Dataset):
    
    exist_paths: Set[str] = set()
    
    def __init__(
        self,
        image_dir: str,
        data_path: Optional[Union[str, List[str]]] = None,
        data: Optional[List[Dict]] = None,
        max_pixels: Optional[int] = None,
        multiple_of: Optional[int] = None,
        square_center_crop: bool = False,
        force_size: Union[int, Tuple[int, int], None] = None,
        begin_with_bg: bool = False,
        debug_config: Dict[str, Any] = {},
    ):
        if data is None and data_path is None:
            raise ValueError("You must specify either `data` or `data_path`.")
        if data is not None and data_path is not None:
            raise ValueError("You must specify only one of `data` or `data_path`.")
        if isinstance(data_path, str):
            data_path = [data_path]
        
        self.data = data or []
        self.data_path = data_path
        self.image_dir = image_dir
        self.max_pixels = max_pixels
        self.multiple_of = multiple_of
        self.square_center_crop = square_center_crop
        self.force_size = force_size
        self.begin_with_bg = begin_with_bg
        self.debug_config = debug_config
        if data_path is not None:
            for sub_data_path in data_path:
                data_items = load_json_file(sub_data_path)
                self.inplace_and_verify_data(data_items, image_dir)
                self.data.extend(data_items)

    @staticmethod
    def build_sample_key_from_relpath(rel_path: str) -> str:
        rel_no_ext = os.path.splitext(rel_path)[0]
        sample_key = rel_no_ext.replace("\\", "__").replace("/", "__")
        return sample_key if sample_key else "sample"

    @classmethod
    def build_sample_key(cls, item: Dict[str, Any]) -> str:
        input_images = item.get("input_images") or []
        output_images = item.get("output_images") or []
        ref_path = input_images[0] if input_images else (output_images[0] if output_images else "")
        return cls.build_sample_key_from_relpath(ref_path)
    
    @staticmethod
    def inplace_and_verify_data(data_items, image_dir):
        """
        Verify:
        1. all items have this schema: {"prompt": str, "input_images": List[str], "output_images": List[str]}
        2. all images exist
        """
        for item in data_items:
            if "prompt" not in item or "input_images" not in item or "output_images" not in item:
                raise ValueError("Each data item must have 'prompt', 'input_images', and 'output_images' fields.")
            if not isinstance(item["prompt"], str):
                raise ValueError("'prompt' must be a string.")
            if not isinstance(item["input_images"], list) or not all(isinstance(i, str) for i in item["input_images"]):
                raise ValueError("'input_images' must be a list of strings.")
            if not isinstance(item["output_images"], list) or not all(isinstance(i, str) for i in item["output_images"]):
                raise ValueError("'output_images' must be a list of strings.")
            item.setdefault("sample_key", TI2IDataset.build_sample_key(item))
            for lst in [item["input_images"], item["output_images"]]:
                for idx in range(len(lst)):
                    img_path = lst[idx]
                    full_path = os.path.join(image_dir, img_path)
                    if full_path not in TI2IDataset.exist_paths and not os.path.exists(full_path):
                        raise FileNotFoundError(f"Image file {full_path} does not exist.")
                    TI2IDataset.exist_paths.add(full_path)
                    lst[idx] = full_path
    
    def apply_center_crop_non_square(self, img: Image.Image, cfg: dict) -> Image.Image:
        """
        Apply non-square center crop to the image based on configuration.
        
        Args:
            img: Input PIL Image
            cfg: Configuration dictionary, e.g.:
                {
                    "prob_crop": 0.8,
                    "crop_ratio_min": 0.2,
                    "crop_ratio_max": 0.3,
                    "tick": 32,
                }
        Returns:
            Cropped PIL Image
        Examples:
            ```
            e.g. cfg = {
                "prob_crop": 0.8,
                "crop_ratio_min": 0.2,
                "crop_ratio_max": 0.3,
                "tick": 32,
            }
            in this case,
                1 - prob_crop for not crop,
                prob_crop / 2 for width crop, (both left and right)
                prob_crop / 2 for height crop. (both top and bottom)
            crop range: [ceiling(size * crop_ratio_min), floor(size * crop_ratio_max)]
                here,
                    ceiling and floor use "tick" as the quantization unit.
                    size refers to the width or height before crop.
            e.g.
                for width crop,
                for c ~ U[ceiling(size * crop_ratio_min), floor(size * crop_ratio_max)],
                left_margin = right_margin = c,
                remain width: RawWidth - c * 2
            ```
        """
        
        
        prob_crop = cfg.get("prob_crop", 0.0)
        
        # Generate random number [0.0, 1.0)
        rand_val = random.random()
        
        # Case 1: No crop (probability = 1 - prob_crop)
        if rand_val >= prob_crop:
            return img

        tick = cfg.get("tick", 32)
        crop_ratio_min = cfg.get("crop_ratio_min", 0.1)
        crop_ratio_max = cfg.get("crop_ratio_max", 0.2)
        
        width, height = img.size
        
        # Case 2: Width Crop
        # Probability interval: [0, prob_crop / 2)
        if rand_val < (prob_crop / 2):
            mode = "width"
            size = width
        # Case 3: Height Crop
        # Probability interval: [prob_crop / 2, prob_crop)
        else:
            mode = "height"
            size = height

        # Calculate crop range [min_c, max_c]
        # ceiling(size * crop_ratio_min) with tick quantization
        min_c = math.ceil((size * crop_ratio_min) / tick) * tick
        
        # floor(size * crop_ratio_max) with tick quantization
        max_c = math.floor((size * crop_ratio_max) / tick) * tick
        
        # Prevent boundary case where max_c is less than min_c
        if max_c < min_c:
            max_c = min_c

        # Does c have to be a multiple of tick?
        # According to docstring "ceiling and floor use tick", it usually means selected c is also aligned with tick.
        # We randomly select a multiple of tick between min_c and max_c.
        tick_min = int(min_c // tick)
        tick_max = int(max_c // tick)
        
        # Randomly select within the range of tick multiples
        c = random.randint(tick_min, tick_max) * tick

        # Execute crop
        # PIL crop format: (left, top, right, bottom)
        if mode == "width":
            # Subtract c from both left and right
            # left = c, right = width - c
            # top = 0, bottom = height
            left = c
            right = width - c
            top = 0
            bottom = height
        else:
            # Subtract c from both top and bottom
            # left = 0, right = width
            # top = c, bottom = height - c
            left = 0
            right = width
            top = c
            bottom = height - c
        
        return img.crop((left, top, right, bottom))
    
    def preprocess_image(self, image):
        image = exif_transpose(image)
        if not image.mode == "RGBA":
            image = image.convert("RGBA")
        if self.square_center_crop:
            width, height = image.size
            min_dim = min(width, height)
            left = (width - min_dim) // 2
            top = (height - min_dim) // 2
            image = F.crop(image, top, left, min_dim, min_dim)
        if self.force_size:
            if isinstance(self.force_size, int):
                size = (self.force_size, self.force_size)
            else:
                size = self.force_size
            image = image.resize(size, resample=PIL.Image.LANCZOS)
        if (cfg := self.debug_config.get("center_crop_into_non_square", None)):
            image = self.apply_center_crop_non_square(image, cfg)
        return image

    def __len__(self):
        return len(self.data)
    
    def process_image_batch_to_pixel_constraint(self, *args):
        """Each item of args should be a PIL Image or a list of PIL Images."""
        
        # import torch.distributed as dist
        # local_rank = dist.get_rank() if dist.is_initialized() else 0
        
        # raw_sizes = []
        # 1. Calculate total pixels of all current images
        current_pixels = 0
        for arg in args:
            if isinstance(arg, list):
                # raw_sizes.append([(img.width, img.height) for img in arg])
                for img in arg:
                    current_pixels += img.width * img.height
            else:
                current_pixels += arg.width * arg.height
                # raw_sizes.append((arg.width, arg.height))

        # 2. Calculate scale ratio (Ratio)
        # If max_pixels is set and current total pixels exceed it, calculate downscale ratio
        # Area ratio = max / current, so side length ratio = sqrt(max / current)
        ratio = 1.0
        # print(f"{local_rank=}, {current_pixels=}, {self.max_pixels=}")
        if self.max_pixels is not None and current_pixels > self.max_pixels:
            ratio = math.sqrt(self.max_pixels / current_pixels)

        # Define processing function for single image (closure)
        def process_image(img):
            # A. Resize (if needed)
            if ratio < 1.0:
                new_w = int(img.width * ratio)
                new_h = int(img.height * ratio)
                # Use high quality resampling
                img = img.resize((new_w, new_h), resample=Image.Resampling.LANCZOS)
            
            # B. Center Crop to multiple of multiple_of (if needed)
            if self.multiple_of is not None and self.multiple_of > 1:
                w, h = img.size
                
                # Calculate target size (floor to nearest multiple)
                target_w = w - (w % self.multiple_of)
                target_h = h - (h % self.multiple_of)
                
                if target_w != w or target_h != h:
                    # Calculate coordinates for Center Crop
                    left = (w - target_w) // 2
                    top = (h - target_h) // 2
                    right = left + target_w
                    bottom = top + target_h
                    
                    img = img.crop((left, top, right, bottom))
            return img

        # 3. Build return value according to original structure of args
        new_args = []
        for arg in args:
            if isinstance(arg, list):
                # Process each image in the list
                new_args.append([process_image(img) for img in arg])
            else:
                # Process single image
                new_args.append(process_image(arg))
        
        # new_sizes = []
        # for arg in new_args:
        #     if isinstance(arg, list):
        #         new_sizes.append([(img.width, img.height) for img in arg])
        #     else:
        #         new_sizes.append((arg.width, arg.height))
        # print(f"[rank {local_rank}] Sizes: {raw_sizes} -> {new_sizes} (ratio: {ratio:.4f})", flush=True)
        
        return tuple(new_args)
        

    def __getitem__(self, index):
        item = self.data[index]
        example = {}
        input_images = []
        for img_path in item["input_images"]:
            image = Image.open(img_path).convert("RGBA")
            image = self.preprocess_image(image)
            input_images.append(image)
        output_images = []
        for img_path in item["output_images"]:
            image = Image.open(img_path).convert("RGBA")
            image = self.preprocess_image(image)
            output_images.append(image)
            
        if not self.debug_config.get("skip_pixel_constraints", False):
            input_images, output_images = self.process_image_batch_to_pixel_constraint(input_images, output_images)
        
        input_images: List[PIL.Image.Image]
        output_images: List[PIL.Image.Image]
        
        if input_images and self.debug_config.get("concat_input_images", False):
            input_images = [concat_images(input_images)]
        
        if output_images and self.debug_config.get("concat_output_images", False):
            output_images = [concat_images(output_images)]
        
        if len(input_images) > 0:
            example["input_images"] = input_images  # (N, C, H, W)
        example["output_images"] = output_images  # (M, C, H, W)
        example["prompt"] = item["prompt"]
        if "input_images" in item:
            example["input_image_paths"] = list(item["input_images"])
        example["output_image_paths"] = list(item["output_images"])
        example["sample_key"] = item.get("sample_key", self.build_sample_key(item))
        example["begin_with_bg"] = bool(item.get("begin_with_bg", self.begin_with_bg))
        return example

DatasetManager.public_default_class = TI2IDataset
DatasetManager.public_classes['TI2IDataset'] = TI2IDataset

def verify(config_path: str):
    manager = DatasetManager(config_path)
    datasets = manager.config['datasets']
    print(f"Found {len(datasets)} datasets in configuration.")
    for idx, name in enumerate(datasets):
        print(f"Verifying dataset {idx + 1}/{len(datasets)}: {name}")
        try:
            dataset = manager._load_dataset(name)
            # print in cyan
            print(f"  \033[96mDataset {name} loaded successfully with {len(dataset)} samples.\033[0m")
            del dataset
            del manager.cache[name]
        except Exception as e:
            # print in red
            print(f"  \033[91mFailed to load dataset {name}: {e}\033[0m")

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: python3 alpha.data <config_path>")
        sys.exit(1)
    config_path = sys.argv[1]
    verify(config_path)
